name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  specs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        ruby_version:
          - 2.7.8
          - 3.0.6
          - 3.1.4
          - 3.2.2
          - 3.3.0
          - jruby-9.4.5.0
        gemfile:
          - gemfiles/Gemfile.activesupport-5.x
          - gemfiles/Gemfile.activesupport-6.x
          - gemfiles/Gemfile.activesupport-7.x

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ matrix.ruby_version }}
            bundler-cache: true

      - name: Run rspec
        run: bundle exec rspec
