name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  specs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        ruby_version:
          - 2.6.9
          - 2.7.5
          - 3.0.3
          - 3.1.3
          - 3.2.1
          - jruby-9.2.14.0
        gemfile:
          - gemfiles/Gemfile.activesupport-5.x
          - gemfiles/Gemfile.activesupport-6.x
          - gemfiles/Gemfile.activesupport-7.x
        exclude:
          - ruby_version: 2.6.9
            gemfile: gemfiles/Gemfile.activesupport-7.x
          - ruby_version: jruby-9.2.14.0
            gemfile: gemfiles/Gemfile.activesupport-7.x

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ matrix.ruby_version }}
            bundler-cache: true

      - name: Run rspec
        run: bundle exec rspec
